Controllers/CompanyListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Caas_ProjectTracker.Models;

namespace Caas_ProjectTracker.Controllers
{
    public class CompanyListsController : Controller
    {
        private CaasConsultingllcEntities db = new CaasConsultingllcEntities();

        // GET: CompanyLists
        public ActionResult Index()
        {
            return View(db.CompanyLists.ToList());
        }

        // GET: CompanyLists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyList companyList = db.CompanyLists.Find(id);
            if (companyList == null)
            {
                return HttpNotFound();
            }
            return View(companyList);
        }

        // GET: CompanyLists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CompanyLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyID,CompanyName,CorporateAddress,City,Country,PostalCode,Phone,Website,Notes,State")] CompanyList companyList)
        {
            if (ModelState.IsValid)
            {
                db.CompanyLists.Add(companyList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(companyList);
        }

        // GET: CompanyLists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyList companyList = db.CompanyLists.Find(id);
            if (companyList == null)
            {
                return HttpNotFound();
            }
            return View(companyList);
        }

        // POST: CompanyLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyID,CompanyName,CorporateAddress,City,Country,PostalCode,Phone,Website,Notes,State")] CompanyList companyList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(companyList);
        }

        // GET: CompanyLists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyList companyList = db.CompanyLists.Find(id);
            if (companyList == null)
            {
                return HttpNotFound();
            }
            return View(companyList);
        }

        // POST: CompanyLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompanyList companyList = db.CompanyLists.Find(id);
            db.CompanyLists.Remove(companyList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Caas_ProjectTracker.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "CAAS Project Tracking Portal (CPTP)";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "For General Info:";

            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    CAAS Consulting, LLC<br />
    Chandler, AZ<br />
    <abbr title="Phone">P:</abbr>
    480-***-****
</address>

<address>
    <strong>Infor:</strong>   <a href="mailto:Support@example.com">Eric.Cassadore@CassConsult.com</a><br />
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<a id="top"></a>
<div class="jumbotron" style="border:1px solid #ffffff; box-shadow:0px 5px 10px #494949;">
    <h1 style="color: bisque; font-family: 'Bodoni MT';">Contract Tracking Portal (CTP)</h1>
    <p class="lead" style="color:white;">Potentional customers, onboarding tracking and existing contracts management tool.</p>
    <p><a href="~/Home/About" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row" style="background: #f6f4e8; border: 1px solid #cccccc">
    <div class="col-md-4">
        <div id="headerOne"><h2 style="color: darkcyan;">Step 1: Company</h2></div>
        <p><a class="btn btn-default" href="~/CompanyLists/Index">Review List of Companies &raquo;</a></p>
        <p>
            Here you can lookup company contact information and confirm a company is listed.
            A company must be listed before entering customer information. If the company is
            listed, proceed to step 2.
        </p>
        <h3 style="color: darkcyan;">Options:</h3>
        <h4 style="color: dimgray;">Company Lookup</h4>

        @using (Html.BeginForm("Index", "CompanyLists", FormMethod.Get))
        {
            <p>
                @Html.TextBox("SearchString")
                <input type="submit" value="Search" />
            </p>
        }
    </div>
    <div class="col-md-4">
        <h2 style="color: darkcyan;">Step 2: Customers</h2>
        <p><a class="btn btn-default" href="~/Customers/Index">Review List of Customers &raquo;</a></p>
        <p>Enter customer information for possible contracts and opportunities here. There may be multiple customers from one company.</p>

    </div>
    <div class="col-md-4">
        <h2 style="color: darkcyan;">Step 3: Projects</h2>
        <p><a class="btn btn-default" href="~/Projects/Index">Review Projects/Contracts &raquo;</a></p>
        <p>
            List of projects and contracts showing which are active as well as pipeline probability.
            Customers with probability ratings 90 and above are tracked here.
        </p>
        <h3 style="color: darkcyan;">Options:</h3>
        <div id="projectdates" style="text-align: left;">
            <div class="demo-section k-content wide" style="display: inline-block; background: #f6f4e8">
                <h4 style="color: dimgray;">Project Date Range</h4>
                <div id="daterangepicker" title="daterangepicker" style="background: #f6f4e8"></div>
            </div>
            <script>
                $(document).ready(function () {
                    $("#daterangepicker").kendoDateRangePicker();
                });
            </script>
            <p></p>
        </div>
        @*<div class="demo-section k-content">

            <h4 style="color: darkcyan;">Start date:</h4>
            <input id="start" style="width: 100%;" value="10/10/2011" />

            <h4 style="margin-top: 1em; color: darkcyan; ">End date:</h4>
            <input id="end" style="width: 100%;" value="10/10/2012" />

        </div>
        <script>
            $(document).ready(function () {
                function startChange() {
                    var startDate = start.value(),
                        endDate = end.value();

                    if (startDate) {
                        startDate = new Date(startDate);
                        startDate.setDate(startDate.getDate());
                        end.min(startDate);
                    } else if (endDate) {
                        start.max(new Date(endDate));
                    } else {
                        endDate = new Date();
                        start.max(endDate);
                        end.min(endDate);
                    }
                }

                function endChange() {
                    var endDate = end.value(),
                        startDate = start.value

                    if (endDate) {
                        endDate = new Date(endDate);
                        endDate.setDate(endDate.getDate());
                        start.max(endDate);
                    } else if (startDate) {
                        end.min(new Date(startDate));
                    } else {
                        endDate = new Date();
                        start.max(endDate);
                        end.min(endDate);
                    }
                }

                var start = $("#start").kendoDatePicker({
                    change: startChange
                }).data("kendoDatePicker");

                var end = $("#end").kendoDatePicker({
                    change: endChange
                }).data("kendoDatePicker");

                start.max(end.value());
                end.min(start.value());
            });
        </script>*@
    </div>
</div>
<!--Options Row-->
<div class="row">
    <div class="col-md-4">

    </div>

    <div class="col-md-4">
        <p></p>
    </div>

    <div class="col-md-4">
        
    </div>
</div>

<a href="#top">Go to top</a>